directly use socat to append the remote peers

diff --git a/client b/client
--- a/client
+++ b/client
@@ -16,15 +16,14 @@ local_interface="${1}"
 fang_server_ip="${2}"
 fang_server_port="${3}"
 
-if ! peers=$(socat "TCP:${fang_server_ip}:${fang_server_port}",connect-timeout=${TIMEOUT} -); then
-	echo "couldn't get the list of peers"
-	exit 1
-fi
-
 PEERS_FILE=$(mktemp /tmp/snakebite.XXXXXX)
 trap 'rm "${PEERS_FILE}"' EXIT
 
 wg showconf "${local_interface}" > "${PEERS_FILE}" # use local configuration as base
-echo "${peers}" >> "${PEERS_FILE}" # and append the response
+
+if ! socat "TCP:${fang_server_ip}:${fang_server_port}",connect-timeout=${TIMEOUT} OPEN:"${PEERS_FILE}",append; then
+	echo "couldn't get the list of peers"
+	exit 1
+fi
 
 wg syncconf "${local_interface}" "${PEERS_FILE}"
